### PR TITLE
fix deepcopy

### LINKED ISSUE #39: JSON.parse(JSON.stringify(stats)) broken when used with es7
on appear.in we use babel-polyfill which results in JSON.stringify(new Map()) returning "[]" (which, as @jan-ivar [found out](http://stackoverflow.com/questions/40841799/es7-map-json-adds-square-brackets), is correct ES7).

This breaks the use of JSON.parse(JSON.stringify(stats)) used for deep-copying.

### PR DESCRIPTION
**Pull request by fippo**
fixes #39

### CODE REVIEW

File: rtcstats.js [hunk 1]
```diff
@@ -1,5 +1,13 @@
 'use strict';
 (function() {
+  function serializeMap(m) {
+    if (!m.entries) return m;
+    var o = {};
+    for (let [k, v] of m) {
+      o[k] = m;
```
Comment (gordonklaus) [inline rtcstats.js]: s/m/v/

File: rtcstats.js [hunk 2]
```diff
@@ -1,5 +1,13 @@
 'use strict';
 (function() {
+  function serializeMap(m) {
```
Comment (gordonklaus) [inline rtcstats.js]: Maybe call it maplike2Object or something. It's not actually serializing

File: rtcstats.js [hunk 3]
```diff
@@ -300,7 +308,7 @@
   // apply a delta compression to the stats report. Reduces size by ~90%.
   // To reduce further, report keys could be compressed.
   function deltaCompression(oldStats, newStats) {
-    newStats = JSON.parse(JSON.stringify(newStats));
+    newStats = JSON.parse(JSON.stringify(serializeMap(newStats)));
```
Comment (gordonklaus) [inline rtcstats.js]: If you do serializeMap first thing in getstats then this becomes redundant

File: rtcstats.js [hunk 4]
```diff
@@ -1,5 +1,15 @@
 'use strict';
 (function() {
+  // transforms a maplike to an object. Mostly for getStats +
+  // JSON.parse(JSON.stringify())
+  function m2o(m) {
```
Comment (dagingaa) [inline rtcstats.js]: Personally I prefer writing things out verbatime, so `mapToObject`, makes it easier to read. Same with the below, it gets smaller in size, but compilers do those things, I want to read and understand easily

Comment (fippo) [reply rtcstats.js]: i would not assume compilers or minifiers here, this thing is intended to be used via script tags

Comment (dagingaa) [reply rtcstats.js]: That's not really a reason not to do it though, jQuery has readable source code, and minifies it for inclusion in script tags :P I say it because splitscreen.js is very bad mostly because at the beginning most of the source code for it was written like this. I don't care much about the content, it's a simple function to convert, but the name here needs to be more descriptive imo. Otherwise I'm just going to assume you're referencing http://www.m2o.it/m2o/home ;)

**Comment by fippo** [comment]
trying this out locally...

**Comment by fippo** [comment]
and this doesn't work :-(

File: rtcstats.js [hunk 5]
```diff
@@ -1,5 +1,17 @@
 'use strict';
 (function() {
+  // transforms a maplike to an object. Mostly for getStats +
+  // JSON.parse(JSON.stringify())
+  function map2obj(m) {
+    if (!m.entries) {
+      return m;
+    }
+    var o = {};
+    m.forEach(function(k, v) {
```
Comment (fippo) [inline rtcstats.js]: mixed up order, its value, key

Comment (fippo) [reply rtcstats.js]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach

**Comment by fippo** [comment]
latest version works.
